# Generated by Django 5.2.7 on 2025-10-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='telegramlink',
            name='link_type',
            field=models.CharField(choices=[('channel', 'Channel'), ('group', 'Group')], default='other', max_length=20),
        ),
    ]
