# Generated by Django 5.2.7 on 2025-10-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_comment_is_active_alter_telegramlink_link_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramlink',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('programming', 'Programming'), ('web_dev', 'Web Development'), ('mobile_dev', 'Mobile Development'), ('ai_ml', 'AI & Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain & Crypto'), ('business', 'Business'), ('entrepreneurship', 'Entrepreneurship'), ('marketing', 'Marketing'), ('finance', 'Finance & Investing'), ('crypto_trading', 'Crypto Trading'), ('education', 'Education'), ('language', 'Language Learning'), ('programming_courses', 'Programming Courses'), ('entertainment', 'Entertainment'), ('gaming', 'Gaming'), ('movies_tv', 'Movies & TV Shows'), ('music', 'Music'), ('anime', 'Anime & Manga'), ('social', 'Social'), ('dating', 'Dating'), ('local', 'Local Communities'), ('news', 'News'), ('politics', 'Politics'), ('tech_news', 'Tech News'), ('health', 'Health & Wellness'), ('fitness', 'Fitness'), ('mental_health', 'Mental Health'), ('travel', 'Travel'), ('food', 'Food & Cooking'), ('sports', 'Sports'), ('fashion', 'Fashion'), ('india', 'India'), ('usa', 'USA'), ('europe', 'Europe'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
